 
clear variables;close all;userpath('clear');restoredefaultpath;clc;

currdir = pwd;
restoredefaultpath;
addpath([currdir,'/helpfunctions']); 

varNames = strtrim({ ...
    'EZGDP','USGDP','UKGDP','CHGDP', ...
    'EZCPI','USCPI','UKCPI','CHCPI', ...
    'EZRR','USRR','UKRR','USDEUR','USDGBP','VIX ','POIL'...
});

% --- If you want to reorder relative to the MAT file’s original order,
% put here the positions of the above variables in the original order.
% Leave [] to keep the MAT file order.
varOrderIdx = [];
spec = "90Q1_25Q4_soc1_dio1_US_3shocks_Ejercicio1_500K";
MatFolder = fullfile(currdir, 'results/matfiles');
OutputFolder = fullfile(currdir, 'IRFs outputs');

% --- Which shocks to show (pick any subset) --- 
shocksToPlot = [1 2 3];

shockNames = {'US Monetary', 'US Supply', 'US Demand'};

% IRFs
plot_irfs_select_shocks(spec, varNames, shocksToPlot, ...
    'MatFolder', MatFolder, ...     
    'CumulativeVarIdx', [], ...       
    'ShockNames', shockNames, ...
    'VarOrderIdx', varOrderIdx, ...     
    'SavePNG', true, ...
    'SaveEPS', false, ...
    'PngFolder', fullfile(OutputFolder,'IRF plots'), ...
    'EpsFolder', fullfile(OutputFolder,'epsfiles'), ...
    'SaveExcel', true, ...
    'ExcelFolder', fullfile(OutputFolder,'IRF excels')); 

% Histograma
plot_irf_h0_histograms(spec, varNames, shocksToPlot, ...
    'MatFolder', MatFolder, ...
    'ShockNames', shockNames, ...
    'CumulativeVarIdx', [], ...
    'Scale', 1, ...
    'PngFolder', fullfile(OutputFolder,'IRF plots')...
);